import { Appointment } from '../types';

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    title: 'Rutinkontroll',
    providerId: '1',
    providerName: 'Dr. Sara Blank',
    providerAvatar: '/avatars/sara.jpg',
    type: 'Konsultation',
    date: new Date(2026, 1, 3, 10, 0),
    duration: 30,
    location: 'Vårdcentralen Norr',
    notes: 'Årlig hälsokontroll',
    status: 'upcoming',
  },
  {
    id: '2',
    title: 'Uppföljning',
    providerId: '2',
    providerName: 'Johan Svensson',
    providerAvatar: '/avatars/johan.jpg',
    type: 'KBT-session',
    date: new Date(2026, 1, 10, 14, 0),
    duration: 45,
    location: 'Psykologmottagningen',
    notes: 'Fortsatt stresshantering',
    status: 'upcoming',
  },
  {
    id: '3',
    title: 'Blodprov',
    providerId: '3',
    providerName: 'Sjuksköterska Erik',
    providerAvatar: '/avatars/nurse.jpg',
    type: 'Provtagning',
    date: new Date(2026, 1, 6, 9, 0),
    duration: 15,
    location: 'Vårdcentralen Norr',
    status: 'upcoming',
  },
  {
    id: '4',
    title: 'Fysioterapi',
    providerId: '5',
    providerName: 'Fysioterapeut Anna',
    providerAvatar: '/avatars/anna.jpg',
    type: 'Behandling',
    date: new Date(2026, 1, 15, 11, 30),
    duration: 60,
    location: 'Fysioterapimottagningen',
    notes: 'Behandling för ryggbesvär',
    status: 'upcoming',
  },
];
