import { PatientProfile } from '../types';

// Mock patient profiles for admin views
export const mockPatients: PatientProfile[] = [
  {
    id: '1',
    name: 'Erik Svensson',
    firstName: 'Erik',
    lastName: 'Svensson',
    email: 'erik.svensson@example.com',
    avatar: '/avatars/erik.jpg',
    isPremium: true,
    role: 'customer',
    assignedArticleIds: ['1', '2'],
    lastActivity: new Date('2026-01-28T14:30:00'),
    personnummer: '19850312-4567',
    dateOfBirth: '1985-03-12',
    gender: 'man',
    phoneNumber: '070-123 45 67',
    address: {
      street: 'Storgatan 12',
      postalCode: '111 22',
      city: 'Stockholm',
    },
    employer: 'Tech Solutions AB',
    department: 'IT-avdelningen',
    jobTitle: 'Systemutvecklare',
    manager: 'Anna Lindqvist',
    workPhone: '08-123 456 78',
    workEmail: 'erik.svensson@techsolutions.se',
    emergencyContact: {
      name: 'Maria Svensson',
      phone: '070-234 56 78',
      relation: 'Maka',
    },
    insuranceProvider: 'Folksam',
    insuranceNumber: 'FS-123456789',
    bloodType: 'A+',
    allergies: ['Penicillin', 'Jordnötter'],
  },
  {
    id: 'p2',
    name: 'Anna Karlsson',
    firstName: 'Anna',
    lastName: 'Karlsson',
    email: 'anna.karlsson@example.com',
    avatar: '/avatars/default-avatar.jpg',
    isPremium: true,
    role: 'customer',
    assignedArticleIds: ['1', '3'],
    lastActivity: new Date('2026-01-27T10:15:00'),
    personnummer: '19920615-2345',
    dateOfBirth: '1992-06-15',
    gender: 'kvinna',
    phoneNumber: '073-987 65 43',
    address: {
      street: 'Vasagatan 45',
      postalCode: '222 33',
      city: 'Göteborg',
    },
    employer: 'Volvo Group',
    department: 'Marknad & Kommunikation',
    jobTitle: 'Marknadschef',
    manager: 'Per Johansson',
    workPhone: '031-987 65 43',
    workEmail: 'anna.karlsson@volvo.com',
    emergencyContact: {
      name: 'Sven Karlsson',
      phone: '070-876 54 32',
      relation: 'Fader',
    },
    insuranceProvider: 'Länsförsäkringar',
    insuranceNumber: 'LF-987654321',
    bloodType: 'B+',
    allergies: [],
  },
  {
    id: 'p3',
    name: 'Lars Andersson',
    firstName: 'Lars',
    lastName: 'Andersson',
    email: 'lars.andersson@example.com',
    avatar: '/avatars/default-avatar.jpg',
    isPremium: false,
    role: 'customer',
    assignedArticleIds: ['2'],
    lastActivity: new Date('2026-01-26T16:45:00'),
    personnummer: '19780923-8765',
    dateOfBirth: '1978-09-23',
    gender: 'man',
    phoneNumber: '076-543 21 09',
    address: {
      street: 'Drottninggatan 78',
      postalCode: '333 44',
      city: 'Malmö',
    },
    employer: 'Malmö Stad',
    department: 'Socialförvaltningen',
    jobTitle: 'Socialsekreterare',
    manager: 'Karin Bengtsson',
    workPhone: '040-543 21 09',
    workEmail: 'lars.andersson@malmo.se',
    emergencyContact: {
      name: 'Eva Andersson',
      phone: '070-654 32 10',
      relation: 'Maka',
    },
    insuranceProvider: 'If Försäkring',
    insuranceNumber: 'IF-456789123',
    bloodType: 'O+',
    allergies: ['Latex'],
  },
  {
    id: 'p4',
    name: 'Maria Lindström',
    firstName: 'Maria',
    lastName: 'Lindström',
    email: 'maria.lindstrom@example.com',
    avatar: '/avatars/default-avatar.jpg',
    isPremium: true,
    role: 'customer',
    assignedArticleIds: ['1', '2', '3'],
    lastActivity: new Date('2026-01-29T09:00:00'),
    personnummer: '19881204-3456',
    dateOfBirth: '1988-12-04',
    gender: 'kvinna',
    phoneNumber: '072-345 67 89',
    address: {
      street: 'Kungsgatan 23',
      postalCode: '444 55',
      city: 'Uppsala',
    },
    employer: 'Uppsala Universitet',
    department: 'Medicinska fakulteten',
    jobTitle: 'Forskare',
    manager: 'Prof. Anders Holm',
    workPhone: '018-471 00 00',
    workEmail: 'maria.lindstrom@uu.se',
    emergencyContact: {
      name: 'Fredrik Lindström',
      phone: '070-456 78 90',
      relation: 'Make',
    },
    insuranceProvider: 'Trygg-Hansa',
    insuranceNumber: 'TH-789123456',
    bloodType: 'AB+',
    allergies: ['Gluten', 'Katt'],
  },
  {
    id: 'p5',
    name: 'Johan Bergström',
    firstName: 'Johan',
    lastName: 'Bergström',
    email: 'johan.bergstrom@example.com',
    avatar: '/avatars/default-avatar.jpg',
    isPremium: false,
    role: 'customer',
    assignedArticleIds: [],
    lastActivity: new Date('2026-01-25T13:20:00'),
    personnummer: '19950827-6789',
    dateOfBirth: '1995-08-27',
    gender: 'man',
    phoneNumber: '079-876 54 32',
    address: {
      street: 'Birger Jarlsgatan 56',
      postalCode: '555 66',
      city: 'Linköping',
    },
    employer: 'Saab AB',
    department: 'Försvarssystem',
    jobTitle: 'Ingenjör',
    manager: 'Lisa Ek',
    workPhone: '013-180 000',
    workEmail: 'johan.bergstrom@saab.se',
    emergencyContact: {
      name: 'Karin Bergström',
      phone: '070-765 43 21',
      relation: 'Moder',
    },
    insuranceProvider: 'Moderna Försäkringar',
    insuranceNumber: 'MF-321654987',
    bloodType: 'A-',
    allergies: ['Skaldjur'],
  },
];

// Helper function to get patient by ID
export function getPatientById(patientId: string): PatientProfile | undefined {
  return mockPatients.find(p => p.id === patientId);
}

// Helper function to get patients by assigned article ID
export function getPatientsByArticleId(articleId: string): PatientProfile[] {
  return mockPatients.filter(p => p.assignedArticleIds.includes(articleId));
}
